//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1.6-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.02 at 09:41:12 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.springwscgweb.org/types", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cgweb.model;
